var i=void 0,l=!0,p=null,q=!1,s,t=this;function ea(a,b){var c=a.split("."),d=t;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&b!==i?d[f]=b:d=d[f]?d[f]:d[f]={}}
function u(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function fa(a){var b=u(a);return"array"==b||"object"==b&&"number"==typeof a.length}function y(a){return"string"==typeof a}function ga(a){var b=typeof a;return"object"==b&&a!=p||"function"==b}var z="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ha=0;
function ia(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}function ja(a,b){function c(){}c.prototype=b.prototype;a.ya=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ka(a,b){this.x=a;this.y=b};function la(a){this.H=a};function ma(a,b,c,d){0<c?(this.x=a,this.width=c):(this.x=a+c,this.width=-c);0<d?(this.y=b,this.height=d):(this.y=b+d,this.height=-d)};function na(a,b){this.type=a;this.geometry=b}function oa(a){if("rect"==a.type)a=a.geometry.width*a.geometry.height;else if("polygon"==a.type){for(var a=a.geometry.H,b=0,c=a.length-1,d=0;d<a.length;d++)b+=(a[c].x+a[d].x)*(a[c].y-a[d].y),c=d;a=Math.abs(b/2)}else a=0;return a}
function pa(a){if("rect"==a.type)return a;if("polygon"==a.type){for(var a=a.geometry.H,b=a[0].x,c=a[0].x,d=a[0].y,f=a[0].y,e=1;e<a.length;e++)a[e].x>c&&(c=a[e].x),a[e].x<b&&(b=a[e].x),a[e].y>f&&(f=a[e].y),a[e].y<d&&(d=a[e].y);return new na("rect",new ma(b,d,c-b,f-d))}}
function qa(a,b){if("rect"==a.type){var c=a.geometry,d=b({x:c.x,y:c.y}),c=b({x:c.x+c.width,y:c.y+c.height});return new na("rect",new ma(d.x,d.y,c.x-d.x,c.y-d.y))}if("polygon"==a.type){var f=[];A(a.geometry.H,function(a){f.push(b(a))});return new na("polygon",new la(f))}};function ra(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function sa(a){if(!ta.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ua,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(xa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ya,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(za,"&quot;"));return a}var ua=/&/g,xa=/</g,ya=/>/g,za=/\"/g,ta=/[&<>\"]/,Aa={};function Ba(a){return Aa[a]||(Aa[a]=(""+a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};var B=Array.prototype,Ca=B.indexOf?function(a,b,c){return B.indexOf.call(a,b,c)}:function(a,b,c){c=c==p?0:0>c?Math.max(0,a.length+c):c;if(y(a))return!y(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},A=B.forEach?function(a,b,c){B.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=y(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};
function Da(a,b){var c;a:{c=a.length;for(var d=y(a)?a.split(""):a,f=0;f<c;f++)if(f in d&&b.call(i,d[f],f,a)){c=f;break a}c=-1}return 0>c?p:y(a)?a.charAt(c):a[c]}function Ea(a,b){var c=Ca(a,b);0<=c&&B.splice.call(a,c,1)}function Fa(a){return B.concat.apply(B,arguments)}function Ga(a){if("array"==u(a))return Fa(a);for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}function Ha(a,b,c,d){B.splice.apply(a,Ia(arguments,1))}
function Ia(a,b,c){return 2>=arguments.length?B.slice.call(a,b):B.slice.call(a,b,c)}function Ja(a,b){B.sort.call(a,b||Ka)}function Ka(a,b){return a>b?1:a<b?-1:0};var C,La,Ma,Na,Oa;function Pa(){return t.navigator?t.navigator.userAgent:p}function Qa(){return t.navigator}Na=Ma=La=C=q;var Ra;if(Ra=Pa()){var Sa=Qa();C=0==Ra.indexOf("Opera");La=!C&&-1!=Ra.indexOf("MSIE");Ma=!C&&-1!=Ra.indexOf("WebKit");Na=!C&&!Ma&&"Gecko"==Sa.product}var Ua=C,D=La,F=Na,G=Ma,Va=Qa();Oa=-1!=(Va&&Va.platform||"").indexOf("Mac");var Wa=!!Qa()&&-1!=(Qa().appVersion||"").indexOf("X11"),Xa;
a:{var Ya="",H;if(Ua&&t.opera)var Za=t.opera.version,Ya="function"==typeof Za?Za():Za;else if(F?H=/rv\:([^\);]+)(\)|;)/:D?H=/MSIE\s+([^\);]+)(\)|;)/:G&&(H=/WebKit\/(\S+)/),H)var $a=H.exec(Pa()),Ya=$a?$a[1]:"";if(D){var ab,bb=t.document;ab=bb?bb.documentMode:i;if(ab>parseFloat(Ya)){Xa=""+ab;break a}}Xa=Ya}var cb={};
function I(a){var b;if(!(b=cb[a])){b=0;for(var c=ra(""+Xa).split("."),d=ra(""+a).split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",j=d[e]||"",h=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var k=h.exec(g)||["","",""],n=m.exec(j)||["","",""];if(0==k[0].length&&0==n[0].length)break;b=((0==k[1].length?0:parseInt(k[1],10))<(0==n[1].length?0:parseInt(n[1],10))?-1:(0==k[1].length?0:parseInt(k[1],10))>(0==n[1].length?0:parseInt(n[1],10))?1:0)||((0==k[2].length)<(0==
n[2].length)?-1:(0==k[2].length)>(0==n[2].length)?1:0)||(k[2]<n[2]?-1:k[2]>n[2]?1:0)}while(0==b)}b=cb[a]=0<=b}return b}var db={};function eb(){return db[9]||(db[9]=D&&!!document.documentMode&&9<=document.documentMode)};var fb,gb=!D||eb();!F&&!D||D&&eb()||F&&I("1.9.1");D&&I("9");function hb(a){return(a=a.className)&&"function"==typeof a.split?a.split(/\s+/):[]}function ib(a,b){var c=hb(a),d=Ia(arguments,1),f;f=c;for(var e=0,g=0;g<d.length;g++)0<=Ca(f,d[g])||(f.push(d[g]),e++);f=e==d.length;a.className=c.join(" ");return f}function jb(a,b){for(var c=hb(a),d=Ia(arguments,1),f=c,e=0,g=0;g<f.length;g++)0<=Ca(d,f[g])&&(Ha(f,g--,1),e++);a.className=c.join(" ")};function kb(a,b){for(var c in a)b.call(i,a[c],c,a)}var lb="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function mb(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<lb.length;e++)c=lb[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function nb(a,b){kb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in ob?a.setAttribute(ob[d],b):0==d.lastIndexOf("aria-",0)?a.setAttribute(d,b):a[d]=b})}var ob={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function pb(a,b,c){var d=arguments,f=document,e=d[0],g=d[1];if(!gb&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',sa(g.name),'"');if(g.type){e.push(' type="',sa(g.type),'"');var j={};mb(j,g);g=j;delete g.type}e.push(">");e=e.join("")}e=f.createElement(e);g&&(y(g)?e.className=g:"array"==u(g)?ib.apply(p,[e].concat(g)):nb(e,g));2<d.length&&qb(f,e,d);return e}
function qb(a,b,c){function d(c){c&&b.appendChild(y(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];fa(e)&&!(ga(e)&&0<e.nodeType)?A(rb(e)?Ga(e):e,d):d(e)}}function sb(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)}function Db(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function rb(a){if(a&&"number"==typeof a.length){if(ga(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==u(a))return"function"==typeof a.item}return q}function J(a){this.P=a||t.document||document}J.prototype.createElement=function(a){return this.P.createElement(a)};J.prototype.createTextNode=function(a){return this.P.createTextNode(a)};J.prototype.appendChild=function(a,b){a.appendChild(b)};J.prototype.contains=Db;function Eb(a,b){var c=(fb||(fb=new J)).createElement("DIV");c.innerHTML=a(b||Fb,i,i);if(1==c.childNodes.length){var d=c.firstChild;if(1==d.nodeType)return d}return c}var Fb={};!D||eb();var Gb=!D||eb();D&&I("8");!G||I("528");F&&I("1.9b")||D&&I("8")||Ua&&I("9.5")||G&&I("528");!F||I("8");function Hb(){}Hb.prototype.ea=q;Hb.prototype.A=function(){this.ea||(this.ea=l,this.B())};Hb.prototype.B=function(){this.sa&&Ib.apply(p,this.sa)};function Ib(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];fa(d)?Ib.apply(p,d):d&&"function"==typeof d.A&&d.A()}};function K(a,b){this.type=a;this.currentTarget=this.target=b}ja(K,Hb);K.prototype.B=function(){delete this.type;delete this.target;delete this.currentTarget};K.prototype.T=q;K.prototype.xa=l;function Jb(a){Jb[" "](a);return a}Jb[" "]=function(){};function L(a,b){a&&this.r(a,b)}ja(L,K);s=L.prototype;s.target=p;s.relatedTarget=p;s.offsetX=0;s.offsetY=0;s.clientX=0;s.clientY=0;s.screenX=0;s.screenY=0;s.button=0;s.keyCode=0;s.charCode=0;s.ctrlKey=q;s.altKey=q;s.shiftKey=q;s.metaKey=q;
s.r=function(a,b){var c=this.type=a.type;K.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(F){var f;a:{try{Jb(d.nodeName);f=l;break a}catch(e){}f=q}f||(d=p)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=G||a.offsetX!==i?a.offsetX:a.layerX;this.offsetY=G||a.offsetY!==i?a.offsetY:a.layerY;this.clientX=a.clientX!==i?a.clientX:a.pageX;this.clientY=a.clientY!==i?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;delete this.xa;delete this.T};s.B=function(){L.ya.B.call(this);this.relatedTarget=this.currentTarget=this.target=p};function Kb(){}var Lb=0;s=Kb.prototype;s.key=0;s.t=q;s.da=q;s.r=function(a,b,c,d,f,e){if("function"==u(a))this.ha=l;else if(a&&a.handleEvent&&"function"==u(a.handleEvent))this.ha=q;else throw Error("Invalid listener argument");this.C=a;this.ka=b;this.src=c;this.type=d;this.capture=!!f;this.fa=e;this.da=q;this.key=++Lb;this.t=q};s.handleEvent=function(a){return this.ha?this.C.call(this.fa||this.src,a):this.C.handleEvent.call(this.C,a)};var M={},N={},O={},P={};
function Q(a,b,c,d,f){if(b){if("array"==u(b)){for(var e=0;e<b.length;e++)Q(a,b[e],c,d,f);return p}var d=!!d,g=N;b in g||(g[b]={j:0,l:0});g=g[b];d in g||(g[d]={j:0,l:0},g.j++);var g=g[d],j=a[z]||(a[z]=++ha),h;g.l++;if(g[j]){h=g[j];for(e=0;e<h.length;e++)if(g=h[e],g.C==c&&g.fa==f){if(g.t)break;return h[e].key}}else h=g[j]=[],g.j++;e=Mb();e.src=a;g=new Kb;g.r(c,e,a,b,d,f);c=g.key;e.key=c;h.push(g);M[c]=g;O[j]||(O[j]=[]);O[j].push(g);a.addEventListener?(a==t||!a.ra)&&a.addEventListener(b,e,d):a.attachEvent(b in
P?P[b]:P[b]="on"+b,e);return c}throw Error("Invalid event type");}function Mb(){var a=Nb,b=Gb?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b}
function V(a){if(M[a]){var b=M[a];if(!b.t){var c=b.src,d=b.type,f=b.ka,e=b.capture;c.removeEventListener?(c==t||!c.ra)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in P?P[d]:P[d]="on"+d,f);c=c[z]||(c[z]=++ha);f=N[d][e][c];if(O[c]){var g=O[c];Ea(g,b);0==g.length&&delete O[c]}b.t=l;f.ja=l;Ob(d,e,c,f);delete M[a]}}}
function Ob(a,b,c,d){if(!d.D&&d.ja){for(var f=0,e=0;f<d.length;f++)d[f].t?d[f].ka.src=p:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.ja=q;0==e&&(delete N[a][b][c],N[a][b].j--,0==N[a][b].j&&(delete N[a][b],N[a].j--),0==N[a].j&&delete N[a])}}function Pb(a,b,c,d,f){var e=1,b=b[z]||(b[z]=++ha);if(a[b]){a.l--;a=a[b];a.D?a.D++:a.D=1;try{for(var g=a.length,j=0;j<g;j++){var h=a[j];h&&!h.t&&(e&=Qb(h,f)!==q)}}finally{a.D--,Ob(c,d,b,a)}}return Boolean(e)}
function Qb(a,b){var c=a.handleEvent(b);a.da&&V(a.key);return c}
function Nb(a,b){if(!M[a])return l;var c=M[a],d=c.type,f=N;if(!(d in f))return l;var f=f[d],e,g;if(!Gb){var j;if(!(j=b))a:{j=["window","event"];for(var h=t;e=j.shift();)if(h[e]!=p)h=h[e];else{j=p;break a}j=h}e=j;j=l in f;h=q in f;if(j){if(0>e.keyCode||e.returnValue!=i)return l;a:{var m=q;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(k){m=l}if(m||e.returnValue==i)e.returnValue=l}}m=new L;m.r(e,this);e=l;try{if(j){for(var n=[],v=m.currentTarget;v;v=v.parentNode)n.push(v);g=f[l];g.l=g.j;for(var w=n.length-
1;!m.T&&0<=w&&g.l;w--)m.currentTarget=n[w],e&=Pb(g,n[w],d,l,m);if(h){g=f[q];g.l=g.j;for(w=0;!m.T&&w<n.length&&g.l;w++)m.currentTarget=n[w],e&=Pb(g,n[w],d,q,m)}}else e=Qb(c,m)}finally{n&&(n.length=0),m.A()}return e}d=new L(b,this);try{e=Qb(c,d)}finally{d.A()}return e};function W(){return l};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

 The "New" BSD License:

 Copyright (c) 2005-2009, The Dojo Foundation
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
 may be used to endorse or promote products derived from this software
 without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var Rb=function(){function a(a,c){if(!a)return[];if(a.constructor==Array)return a;if(!y(a))return[a];if(y(c)&&(c=y(c)?document.getElementById(c):c,!c))return[];var c=c||document,e=c.ownerDocument||c.documentElement;S=c.contentType&&"application/xml"==c.contentType||Ua&&(c.doctype||"[object XMLDocument]"==e.toString())||!!e&&(D?e.xml:c.xmlVersion||e.xmlVersion);return(e=d(a)(c))&&e.F?e:b(e)}function b(a){if(a&&a.F)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;
E++;if(D&&S){var c=E+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(D&&a.qa)try{for(d=1;e=a[d];d++)va(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0]._zipIdx=E);for(d=1;e=a[d];d++)a[d]._zipIdx!=E&&b.push(e),e._zipIdx=E}return b}function c(a,b){if(!b)return 1;var c=sc(a);return!b[c]?b[c]=1:0}function d(a,b){if(ub){var c=vb[a];if(c&&!b)return c}if(c=wb[a])return c;var c=a.charAt(0),e=-1==a.indexOf(" ");0<=a.indexOf("#")&&
e&&(b=l);if(ub&&!b&&-1==">~+".indexOf(c)&&(!D||-1==a.indexOf(":"))&&!(xb&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var g=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return vb[a]=function(b){try{if(!(9==b.nodeType||e))throw"";var c=b.querySelectorAll(g);D?c.qa=l:c.F=l;return c}catch(f){return d(a,l)(b)}}}var n=a.split(/\s*,\s*/);return wb[a]=2>n.length?f(a):function(a){for(var b=0,c=[],d;d=n[b++];)c=c.concat(f(d)(a));return c}}function f(a){var b=yb(ra(a));if(1==b.length){var c=
e(b[0]);return function(a){if(a=c(a,[]))a.F=l;return a}}return function(a){for(var a=ba(a),c,d,f=b.length,tb,R,g=0;g<f;g++){R=[];c=b[g];d=a.length-1;0<d&&(tb={},R.F=l);d=e(c);for(var n=0;c=a[n];n++)d(c,R,tb);if(!R.length)break;a=R}return R}}function e(a){var b=zb[a.s];if(b)return b;var c=a.ga,c=c?c.G:"",d=m(a,{q:1}),e="*"==a.d,f=document.getElementsByClassName;if(c)f={q:1},e&&(f.d=1),d=m(a,f),"+"==c?b=h(d):"~"==c?b=j(d):">"==c&&(b=g(d));else if(a.id)d=!a.ia&&e?W:m(a,{q:1,id:1}),b=function(b,c){var e;
e=b?new J(9==b.nodeType?b:b.ownerDocument||b.document):fb||(fb=new J);var f=a.id;if(f=(e=y(f)?e.P.getElementById(f):f)&&d(e))if(!(f=9==b.nodeType)){for(f=e.parentNode;f&&!(f==b);)f=f.parentNode;f=!!f}if(f)return ba(e,c)};else if(f&&/\{\s*\[native code\]\s*\}/.test(""+f)&&a.i.length&&!xb)var d=m(a,{q:1,i:1,id:1}),n=a.i.join(" "),b=function(a,b){for(var c=ba(0,b),e,f=0,aa=a.getElementsByClassName(n);e=aa[f++];)d(e,a)&&c.push(e);return c};else!e&&!a.ia?b=function(b,c){for(var d=ba(0,c),e,f=0,aa=b.getElementsByTagName(a.Q());e=
aa[f++];)d.push(e);return d}:(d=m(a,{q:1,d:1,id:1}),b=function(b,c){for(var e=ba(0,c),f,aa=0,g=b.getElementsByTagName(a.Q());f=g[aa++];)d(f,b)&&e.push(f);return e});return zb[a.s]=b}function g(a){a=a||W;return function(b,d,e){for(var f=0,g=b[Ab];b=g[f++];)ca(b)&&(!e||c(b,e))&&a(b,f)&&d.push(b);return d}}function j(a){return function(b,d,e){for(b=b[da];b;){if(ca(b)){if(e&&!c(b,e))break;a(b)&&d.push(b)}b=b[da]}return d}}function h(a){return function(b,d,e){for(;b=b[da];)if(!wa||va(b)){(!e||c(b,e))&&
a(b)&&d.push(b);break}return d}}function m(a,b){if(!a)return W;var b=b||{},c=p;b.q||(c=T(c,va));b.d||"*"!=a.d&&(c=T(c,function(b){return b&&b.tagName==a.Q()}));b.i||A(a.i,function(a,b){var d=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=T(c,function(a){return d.test(a.className)});c.count=b});b.k||A(a.k,function(a){var b=a.name;Ta[b]&&(c=T(c,Ta[b](b,a.value)))});b.z||A(a.z,function(a){var b,d=a.O;a.type&&Bb[a.type]?b=Bb[a.type](d,a.R):d.length&&(b=tc(d));b&&(c=T(c,b))});b.id||a.id&&(c=T(c,function(b){return!!b&&
b.id==a.id}));c||"default"in b||(c=W);return c}function k(a){return v(a)%2}function n(a){return!(v(a)%2)}function v(a){var b=a.parentNode,c=0,d=b[Ab],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&0<=e&&0<=f)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[da])ca(b)&&(b._i=++c,a===b&&(e=c));return e}function w(a){for(;a=a[da];)if(ca(a))return q;return l}function Cb(a){for(;a=a[uc];)if(ca(a))return q;return l}function U(a,b){return!a?"":"class"==b?a.className||"":"for"==
b?a.htmlFor||"":"style"==b?a.style.cssText||"":(S?a.getAttribute(b):a.getAttribute(b,2))||""}function va(a){return 1==a.nodeType}function T(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function yb(a){function b(){0<=j&&(o.id=c(j,r).replace(/\\/g,""),j=-1);if(0<=m){var a=m==r?p:c(m,r);0>">~+".indexOf(a)?o.d=a:o.G=a;m=-1}0<=h&&(o.i.push(c(h+1,r).replace(/\\/g,"")),h=-1)}function c(b,d){return ra(a.slice(b,d))}for(var a=0<=">~+".indexOf(a.slice(-1))?a+
" * ":a+" ",d=[],e=-1,f=-1,g=-1,n=-1,h=-1,j=-1,m=-1,v="",k="",w,r=0,E=a.length,o=p,x=p;v=k,k=a.charAt(r),r<E;r++)if("\\"!=v)if(o||(w=r,o={s:p,k:[],z:[],i:[],d:p,G:p,id:p,Q:function(){return S?this.wa:this.d}},m=r),0<=e)if("]"==k){x.O?x.R=c(g||e+1,r):x.O=c(e+1,r);if((e=x.R)&&('"'==e.charAt(0)||"'"==e.charAt(0)))x.R=e.slice(1,-1);o.z.push(x);x=p;e=g=-1}else"="==k&&(g=0<="|~^$*".indexOf(v)?v:"",x.type=g+k,x.O=c(e+1,r-g.length),g=r+1);else 0<=f?")"==k&&(0<=n&&(x.value=c(f+1,r)),n=f=-1):"#"==k?(b(),j=
r+1):"."==k?(b(),h=r):":"==k?(b(),n=r):"["==k?(b(),e=r,x={}):"("==k?(0<=n&&(x={name:c(n+1,r),value:p},o.k.push(x)),f=r):" "==k&&v!=k&&(b(),0<=n&&o.k.push({name:c(n+1,r)}),o.ia=o.k.length||o.z.length||o.i.length,o.Ba=o.s=c(w,r),o.wa=o.d=o.G?p:o.d||"*",o.d&&(o.d=o.d.toUpperCase()),d.length&&d[d.length-1].G&&(o.ga=d.pop(),o.s=o.ga.s+" "+o.s),d.push(o),o=p);return d}function ba(a,b){var c=b||[];a&&c.push(a);return c}var xb=G&&"BackCompat"==document.compatMode,Ab=document.firstChild.children?"children":
"childNodes",S=q,Bb={"*=":function(a,b){return function(c){return 0<=U(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==U(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+U(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+U(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+U(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return U(c,a)==b}}},wa=
"undefined"==typeof document.firstChild.nextElementSibling,da=!wa?"nextElementSibling":"nextSibling",uc=!wa?"previousElementSibling":"previousSibling",ca=wa?va:W,Ta={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return Cb},"last-child":function(){return w},"only-child":function(){return function(a){return!Cb(a)||!w(a)?q:l}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===
c||3==c)return q}return l}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},not:function(a,b){var c=yb(b)[0],d={q:1};"*"!=c.d&&(d.d=1);c.i.length||(d.i=1);var e=m(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if("odd"==b)return k;if("even"==b)return n;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,g=-1;0<d?0>e?e=e%d&&d+e%d:0<e&&(e>=
d&&(f=e-e%d),e%=d):0>d&&(d*=-1,0<e&&(g=e,e%=d));if(0<d)return function(a){a=v(a);return a>=f&&(0>g||a<=g)&&a%d==e};b=e}var h=parseInt(b,10);return function(a){return v(a)==h}}},tc=D?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return S?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},zb={},wb={},vb={},ub=!!document.querySelectorAll&&(!G||I("526")),E=0,sc=D?function(a){return S?a.getAttribute("_uid")||a.setAttribute("_uid",
++E)||E:a.uniqueID}:function(a){return a._uid||(a._uid=++E)};a.k=Ta;return a}();ea("goog.dom.query",Rb);ea("goog.dom.query.pseudos",Rb.k);function Sb(a,b,c){this.g=a;this.o=b;this.c=c;this.w=[];this.p=[];this.e=this.g.getContext("2d");this.m=l;this.X=q;var d=this;Q(this.g,"mousemove",function(a){if(d.m){var b=Tb(d,a.offsetX,a.offsetY);b?(d.X=q,d.b?d.b!=b&&(d.m=q,Ub(d.o)):(d.b=b,X(d),d.c.fireEvent(Vb,{annotation:d.b,S:a}))):!d.X&&d.b&&(d.m=q,Ub(d.o))}else d.u=a});Y(c,Z,function(){delete d.b;d.m=l});Y(c,Wb,function(){if(!d.m&&d.u){var a=d.b;d.b=Tb(d,d.u.offsetX,d.u.offsetY);d.m=l;a!=d.b?(X(d),d.c.fireEvent(Xb,{annotation:a,S:d.u}),d.c.fireEvent(Vb,
{annotation:d.b,S:d.u})):d.b&&Yb(d.o)}else X(d)})}function Zb(a,b){a.w.push(b);var c=b.shapes[0];"pixel"!=c.units&&(c=qa(c,function(b){return a.c.ta(b)}));a.p[JSON.stringify(b.shapes[0].geometry)]=c;X(a)}function Tb(a,b,c){a=$b(a,b,c);if(0<a.length)return a[0]}
function $b(a,b,c){var d=[];A(a.w,function(f){var e;e=a.p[JSON.stringify(f.shapes[0].geometry)];if("rect"==e.type)e=b<e.geometry.x||c<e.geometry.y||b>e.geometry.x+e.geometry.width||c>e.geometry.y+e.geometry.height?q:l;else if("polygon"==e.type){e=e.geometry.H;for(var g=q,j=e.length-1,h=0;h<e.length;h++)e[h].y>c!=e[j].y>c&&b<(e[j].x-e[h].x)*(c-e[h].y)/(e[j].y-e[h].y)+e[h].x&&(g=!g),j=h;e=g}else e=q;e&&d.push(f)});Ja(d,function(a,b){return oa(a.shapes[0])>oa(b.shapes[0])});return d}
function ac(a,b,c){Da(a.c.ua(),function(){return"rect"==b.type})?bc(a.e,b,c):console.log("WARNING unsupported shape type: "+b.type)}function X(a){a.e.clearRect(0,0,a.g.width,a.g.height);A(a.w,function(b){ac(a,a.p[JSON.stringify(b.shapes[0].geometry)])});if(a.b){var b=a.p[JSON.stringify(a.b.shapes[0].geometry)];ac(a,b,l);b=pa(b).geometry;a.o.show(a.b,{x:b.x,y:b.y+b.height+5})}};function cc(a,b,c){y(b)?dc(a,c,b):kb(b,ia(dc,a))}function dc(a,b,c){a.style[Ba(c)]=b}function ec(a,b,c){var d=F&&(Oa||Wa)&&I("1.9");a.style.left=fc(b,d);a.style.top=fc(c,d)}function gc(a,b,c){if(c==i)throw Error("missing height argument");a.style.width=fc(b,l);a.style.height=fc(c,l)}function fc(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a}
function hc(a,b){var c=a.style;"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*b+")")}function ic(a,b){a.style.display=b?"":"none"};function jc(a,b){function c(c){var c=c.relatedTarget,d;if(!(d=!c||Db(e,c)))if(d=Db(b.editor.element[0],c))d=b.editor.annotation,d=!d?q:d.url==a.src;return d||Db(b.viewer.element[0],c)&&kc(j)?l:q}var d=lc(b.element[0].firstChild),f=new mc,e=pb("div","yuma-annotationlayer");cc(e,"position","relative");gc(e,a.width,a.height);sb(e,a);e.appendChild(a);var g=Eb(nc,{width:a.width,height:a.height});e.appendChild(g);var j=new oc(a,f,b,d),h=Eb(nc,{width:a.width,height:a.height});ic(h,q);e.appendChild(h);var m=
new pc;m.r(h,f);var k=new Sb(g,j,f);new qc(f,e);f.la=function(a){return a};f.ta=function(a){return a};f.ua=function(){return[m]};Q(e,"mouseover",function(a){c(a)||f.fireEvent(rc)});Q(e,"mouseout",function(a){c(a)||f.fireEvent(Z)});vc(j,function(a){c(a)||f.fireEvent(rc)});wc(j,function(a){c(a)||f.fireEvent(Z)});Q(g,"mousedown",function(a){ic(h,l);k.b=i;Ub(k.o);X(k);var b=a.offsetX,a=a.offsetY;m.L=l;m.I();m.a=new ka(b,a);m.c.fireEvent(xc,{offsetX:b,offsetY:a});cc(document.body,"-webkit-user-select",
"none")});Y(f,rc,function(){b.clearViewerHideTimer();hc(g,1)});Y(f,Z,function(){hc(g,0.4)});Y(f,yc,function(c){var e={url:a.src,shapes:[c.shape]};b.publish("beforeAnnotationCreated",e);var f=lc(a),g=c.shape.geometry,c=g.x+f.left-d.left+16,f=g.y+g.height+f.top+window.pageYOffset-d.top+5;b.showEditor(e,{top:window.pageYOffset-d.top,left:0});ec(b.editor.element[0],c,f);console.log(e)});Y(f,zc,function(){ic(h,q);Ac(m)});b.viewer.on("edit",function(c){if(c.url==a.src){ic(h,l);k.b=i;Ub(k.o);X(k);var e=
lc(a),f=c.shapes[0].geometry,c=f.x+e.left-d.left+16,e=f.y+f.height+e.top-d.top+window.pageYOffset+5;ec(b.editor.element[0],0,window.pageYOffset-d.top);b.editor.show();ec(b.editor.element[0],c,e)}});b.subscribe("annotationCreated",function(b){b.url==a.src&&(Ac(m),b.url==a.src&&Zb(k,b))});b.subscribe("annotationsLoaded",function(b){A(b,function(b){b.url==a.src&&Zb(k,b)})});b.subscribe("annotationDeleted",function(b){b.url==a.src&&(b==k.b&&delete k.b,Ea(k.w,b),delete k.p[JSON.stringify(b.shapes[0].geometry)],
X(k));f.fireEvent(Wb)});b.subscribe("annotationEditorHidden",function(){ic(h,q);Ac(m);f.fireEvent(Wb)})}window.Annotator.Plugin.AnnotoriousImagePlugin=function(){function a(a){this.ma=a}a.prototype.pluginInit=function(){var a=this;A(this.ma.getElementsByTagName("img"),function(c){new jc(c,a.annotator)})};return a}();function oc(a,b,c,d){this.W=a;this.na=b;this.h=c;this.J=d;this.K=q;this.aa=[];this.$=[];var f=this;Q(this.h.viewer.element[0],"mouseover",function(a){kc(f)&&(Yb(f),A(f.aa,function(b){b(a)}))});Q(this.h.viewer.element[0],"mouseout",function(a){kc(f)&&(c.clearViewerHideTimer(),Ub(f),A(f.$,function(b){b(a)}))})}function kc(a){var b=a.h.viewer.annotations;return!b||1>b.length?q:b[0].url==a.W.src}function vc(a,b){a.aa.push(b)}function wc(a,b){a.$.push(b)}
function Ub(a){0<=Ca(hb(a.h.viewer.element[0]),"annotator-hide")||(a.K=q,a.v||(a.v=window.setTimeout(function(){a.na.fireEvent(Wb);!a.K&&kc(a)&&(ib(a.h.viewer.element[0],"annotator-hide"),a.h.viewer.annotations=[],delete a.v)},300)))}function Yb(a){a.K=l;a.v&&(window.clearTimeout(a.v),delete a.v)}
oc.prototype.show=function(a,b){jb(this.h.viewer.element[0],"annotator-hide");var c=lc(this.W);ec(this.h.viewer.element[0],0,window.pageYOffset-this.J.top);this.h.viewer.load([a]);ec(this.h.viewer.element[0],c.left-this.J.left+b.x+16,c.top+window.pageYOffset-this.J.top+b.y);Yb(this)};function pc(){}pc.prototype.r=function(a,b){this.g=a;this.c=b;this.e=a.getContext("2d");this.e.lineWidth=1;this.L=q};
pc.prototype.I=function(){var a=this;this.N=Q(this.g,"mousemove",function(b){if(a.L){a.f={x:b.offsetX,y:b.offsetY};a.e.clearRect(0,0,a.g.width,a.g.height);var b=a.f.x-a.a.x,c=a.f.y-a.a.y;a.e.strokeStyle="#000000";a.e.strokeRect(a.a.x+0.5,a.a.y+0.5,b,c);a.e.strokeStyle="#ffffff";0<b&&0<c?a.e.strokeRect(a.a.x+1.5,a.a.y+1.5,b-2,c-2):0<b&&0>c?a.e.strokeRect(a.a.x+1.5,a.a.y-0.5,b-2,c+2):0>b&&0>c?a.e.strokeRect(a.a.x-0.5,a.a.y-0.5,b+2,c+2):a.e.strokeRect(a.a.x-0.5,a.a.y+1.5,b+2,c-2)}});this.Z=Q(this.g,
"mouseup",function(b){a.L=q;var c;if(a.f&&3<Math.abs(a.f.x-a.a.x)&&3<Math.abs(a.f.y-a.a.y)){var d=Bc(a);c=a.c.la({x:d.left,y:d.top});d=a.c.la({x:d.right-1,y:d.bottom-1});c=new na("rect",new ma(c.x,c.y,d.x-c.x,d.y-c.y))}else c=i;c?a.c.fireEvent(yc,{S:b,shape:c,Ca:Bc(a)}):a.c.fireEvent(zc)})};pc.prototype.U=function(){this.N&&(V(this.N),delete this.N);this.Z&&(V(this.Z),delete this.za)};
function Ac(a){a.U();a.e.clearRect(0,0,a.g.width,a.g.height);cc(document.body,"-webkit-user-select","auto");delete a.f}function Bc(a){var b,c;a.f.x>a.a.x?(b=a.f.x,c=a.a.x):(b=a.a.x,c=a.f.x);var d;a.f.y>a.a.y?(d=a.a.y,a=a.f.y):(d=a.f.y,a=a.a.y);return{top:d,right:b,bottom:a,left:c}}
function bc(a,b,c){if("rect"==b.type){var d;c?(c="#fff000",d=1.2):(c="#ffffff",d=1);b=b.geometry;a.strokeStyle="#000000";a.lineWidth=d;a.strokeRect(b.x+0.5,b.y+0.5,b.width+1,b.height+1);a.strokeStyle=c;a.strokeRect(b.x+1.5,b.y+1.5,b.width-1,b.height-1)}};function lc(a){for(var b=0,c=0;a&&!isNaN(a.offsetLeft)&&!isNaN(a.offsetTop);)b+=a.offsetLeft-a.scrollLeft,c+=a.offsetTop-a.scrollTop,a=a.offsetParent;return{top:c,left:b}};function mc(){this.n=[]}function Y(a,b,c){a.n[b]||(a.n[b]=[]);a.n[b].push(c)}mc.prototype.fireEvent=function(a,b){var c=this.n[a];c&&A(c,function(a){a(b)})};var rc="onMouseOverItem",Z="onMouseOutOfItem",Vb="onMouseOverAnnotation",Xb="onMouseOutOfAnnotation",xc="onSelectionStarted",zc="onSelectionCanceled",yc="onSelectionCompleted",Wb="beforePopupHide";function qc(a,b,c){var d=this;c||(c="Click and Drag to Annotate");this.element=Eb(Cc,{va:c});this.c=a;this.Y=Rb(".annotorious-hint-msg",this.element)[0];this.V=Rb(".annotorious-hint-icon",this.element)[0];this.ca=function(){d.show()};this.ba=function(){Dc(d)};this.I();Dc(this);b.appendChild(this.element)}qc.prototype.I=function(){var a=this;this.pa=Q(this.V,"mouseover",function(){a.show();window.clearTimeout(a.M)});this.oa=Q(this.V,"mouseout",function(){Dc(a)});Y(this.c,rc,this.ca);Y(this.c,Z,this.ba)};
qc.prototype.U=function(){V(this.pa);V(this.oa);var a=this.c.n[rc];a&&Ea(a,this.ca);(a=this.c.n[Z])&&Ea(a,this.ba)};qc.prototype.show=function(){window.clearTimeout(this.M);hc(this.Y,0.8);var a=this;this.M=window.setTimeout(function(){Dc(a)},3E3)};function Dc(a){window.clearTimeout(a.M);hc(a.Y,0)};D&&I(8);"ScriptEngine"in t&&"JScript"==t.ScriptEngine()&&(t.ScriptEngineMajorVersion(),t.ScriptEngineMinorVersion(),t.ScriptEngineBuildVersion());function Ec(a){return"object"===typeof a&&a&&0===a.Aa?a.content:(""+a).replace(Fc,Gc)}var Hc={"\x00":"&#0;",'"':"&quot;","&":"&amp;","'":"&#39;","<":"&lt;",">":"&gt;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\u000c":"&#12;","\r":"&#13;"," ":"&#32;","-":"&#45;","/":"&#47;","=":"&#61;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function Gc(a){return Hc[a]}var Fc=/[\x00\x22\x26\x27\x3c\x3e]/g;function nc(a){return'<canvas class="annotorious-item annotorious-opacity-fade" style="position:absolute; top:0px; left:0px; width:'+Ec(a.width)+"px; height:"+Ec(a.height)+'px; z-index:0" width="'+Ec(a.width)+'" height="'+Ec(a.height)+'"></canvas>'}
function Cc(a){return'<div class="annotorious-hint" style="white-space:nowrap; position:absolute; top:0px; left:0px; pointer-events:none;"><div class="annotorious-hint-msg annotorious-opacity-fade">'+Ec(a.va)+'</div><div class="annotorious-hint-icon" style="pointer-events:auto"></div></div>'};
