var i=void 0,l=!0,n=null,o=!1,t,u=this;function aa(a,b){var c=a.split("."),d=u;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&b!==i?d[f]=b:d=d[f]?d[f]:d[f]={}}
function v(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ba(a){var b=v(a);return"array"==b||"object"==b&&"number"==typeof a.length}function y(a){return"string"==typeof a}function ca(a){var b=typeof a;return"object"==b&&a!=n||"function"==b}var z="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ga=0;
function ha(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}function ia(a,b){function c(){}c.prototype=b.prototype;a.oa=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ja(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function ka(a){if(!la.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ma,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(na,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(oa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(pa,"&quot;"));return a}var ma=/&/g,na=/</g,oa=/>/g,pa=/\"/g,la=/[&<>\"]/,qa={};function ra(a){return qa[a]||(qa[a]=(""+a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};var A,sa,ta,ua,va;function za(){return u.navigator?u.navigator.userAgent:n}function Aa(){return u.navigator}ua=ta=sa=A=o;var Ba;if(Ba=za()){var Ca=Aa();A=0==Ba.indexOf("Opera");sa=!A&&-1!=Ba.indexOf("MSIE");ta=!A&&-1!=Ba.indexOf("WebKit");ua=!A&&!ta&&"Gecko"==Ca.product}var Da=A,B=sa,C=ua,D=ta,Ea=Aa();va=-1!=(Ea&&Ea.platform||"").indexOf("Mac");var Fa=!!Aa()&&-1!=(Aa().appVersion||"").indexOf("X11"),Ga;
a:{var Ha="",Ia;if(Da&&u.opera)var Ja=u.opera.version,Ha="function"==typeof Ja?Ja():Ja;else if(C?Ia=/rv\:([^\);]+)(\)|;)/:B?Ia=/MSIE\s+([^\);]+)(\)|;)/:D&&(Ia=/WebKit\/(\S+)/),Ia)var Ka=Ia.exec(za()),Ha=Ka?Ka[1]:"";if(B){var La,Ma=u.document;La=Ma?Ma.documentMode:i;if(La>parseFloat(Ha)){Ga=""+La;break a}}Ga=Ha}var Na={};
function E(a){var b;if(!(b=Na[a])){b=0;for(var c=ja(""+Ga).split("."),d=ja(""+a).split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",h=d[e]||"",j=RegExp("(\\d*)(\\D*)","g"),k=RegExp("(\\d*)(\\D*)","g");do{var r=j.exec(g)||["","",""],m=k.exec(h)||["","",""];if(0==r[0].length&&0==m[0].length)break;b=((0==r[1].length?0:parseInt(r[1],10))<(0==m[1].length?0:parseInt(m[1],10))?-1:(0==r[1].length?0:parseInt(r[1],10))>(0==m[1].length?0:parseInt(m[1],10))?1:0)||((0==r[2].length)<(0==
m[2].length)?-1:(0==r[2].length)>(0==m[2].length)?1:0)||(r[2]<m[2]?-1:r[2]>m[2]?1:0)}while(0==b)}b=Na[a]=0<=b}return b}var Oa={};function Pa(){return Oa[9]||(Oa[9]=B&&!!document.documentMode&&9<=document.documentMode)};var F=Array.prototype,Qa=F.indexOf?function(a,b,c){return F.indexOf.call(a,b,c)}:function(a,b,c){c=c==n?0:0>c?Math.max(0,a.length+c):c;if(y(a))return!y(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},H=F.forEach?function(a,b,c){F.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=y(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};
function Ra(a,b){var c;a:{c=a.length;for(var d=y(a)?a.split(""):a,f=0;f<c;f++)if(f in d&&b.call(i,d[f],f,a)){c=f;break a}c=-1}return 0>c?n:y(a)?a.charAt(c):a[c]}function Sa(a,b){var c=Qa(a,b);0<=c&&F.splice.call(a,c,1)}function Ta(a){return F.concat.apply(F,arguments)}function Wa(a){if("array"==v(a))return Ta(a);for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}function Xa(a,b,c,d){F.splice.apply(a,Ya(arguments,1))}
function Ya(a,b,c){return 2>=arguments.length?F.slice.call(a,b):F.slice.call(a,b,c)}function Za(a,b){F.sort.call(a,b||$a)}function $a(a,b){return a>b?1:a<b?-1:0};var ab,bb=!B||Pa();!C&&!B||B&&Pa()||C&&E("1.9.1");B&&E("9");function cb(a){return(a=a.className)&&"function"==typeof a.split?a.split(/\s+/):[]}function db(a,b){var c=cb(a),d=Ya(arguments,1),f;f=c;for(var e=0,g=0;g<d.length;g++)0<=Qa(f,d[g])||(f.push(d[g]),e++);f=e==d.length;a.className=c.join(" ");return f}function eb(a,b){for(var c=cb(a),d=Ya(arguments,1),f=c,e=0,g=0;g<f.length;g++)0<=Qa(d,f[g])&&(Xa(f,g--,1),e++);a.className=c.join(" ")};function fb(a,b){for(var c in a)b.call(i,a[c],c,a)}var gb="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function hb(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<gb.length;e++)c=gb[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function ib(a,b){fb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in jb?a.setAttribute(jb[d],b):0==d.lastIndexOf("aria-",0)?a.setAttribute(d,b):a[d]=b})}var jb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function kb(a,b,c){var d=arguments,f=document,e=d[0],g=d[1];if(!bb&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',ka(g.name),'"');if(g.type){e.push(' type="',ka(g.type),'"');var h={};hb(h,g);g=h;delete g.type}e.push(">");e=e.join("")}e=f.createElement(e);g&&(y(g)?e.className=g:"array"==v(g)?db.apply(n,[e].concat(g)):ib(e,g));2<d.length&&lb(f,e,d);return e}
function lb(a,b,c){function d(c){c&&b.appendChild(y(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];ba(e)&&!(ca(e)&&0<e.nodeType)?H(mb(e)?Wa(e):e,d):d(e)}}function nb(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)}function ob(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function mb(a){if(a&&"number"==typeof a.length){if(ca(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==v(a))return"function"==typeof a.item}return o}function I(a){this.R=a||u.document||document}I.prototype.createElement=function(a){return this.R.createElement(a)};I.prototype.createTextNode=function(a){return this.R.createTextNode(a)};I.prototype.appendChild=function(a,b){a.appendChild(b)};I.prototype.contains=ob;var J="ontouchstart"in window,K={qa:J?"touchstart":"mousedown",W:J?"touchenter":"mouseover",ra:J?"touchmove":"mousemove",sa:J?"touchend":"mouseup",V:J?"touchleave":"mouseout",Ea:J?"touchend":"click"};K.D=J;K.Ha=J?"TouchEvent":"MouseEvent";K.Ia=J?"initTouchEvent":"initMouseEvent";J&&db(document.getElementsByTagName("html")[0],"hasTouch");function pb(a,b){this.x=a;this.y=b};function qb(a){this.points=a}function rb(a){for(var b=0,c=a.length-1,d=0;d<a.length;d++)b+=(a[c].x+a[d].x)*(a[c].y-a[d].y),c=d;return b/2}
function sb(a,b){var c,d;d=c=0;for(var f,e=a.length-1,g=0;g<a.length;g++)f=a[g].x*a[e].y-a[e].x*a[g].y,c+=(a[g].x+a[e].x)*f,d+=(a[g].y+a[e].y)*f,e=g;f=6*rb(a);c=Math.abs(c/f);d=Math.abs(d/f);f=[];for(e=0;e<a.length;e++){var g=a[e],h=(0>rb(a)?-1:1)*b,j=g.x-c,k=g.y-d,r=0<h?1:0>h?-1:0,h=Math.sqrt(Math.pow(h,2)/(1+Math.pow(j/k,2)));f.push({x:g.x+Math.abs(j/k*h)*(0<j?1:0>j?-1:0)*r,y:g.y+Math.abs(h)*(0<k?1:0>k?-1:0)*r})}return f};function tb(a,b,c,d){0<c?(this.x=a,this.width=c):(this.x=a+c,this.width=-c);0<d?(this.y=b,this.height=d):(this.y=b+d,this.height=-d)};function Db(a,b){this.type=a;this.geometry=b}function Eb(a){return"rect"==a.type?a.geometry.width*a.geometry.height:"polygon"==a.type?Math.abs(rb(a.geometry.points)):0}function Fb(a){if("rect"==a.type)return a;if("polygon"==a.type){for(var a=a.geometry.points,b=a[0].x,c=a[0].x,d=a[0].y,f=a[0].y,e=1;e<a.length;e++)a[e].x>c&&(c=a[e].x),a[e].x<b&&(b=a[e].x),a[e].y>f&&(f=a[e].y),a[e].y<d&&(d=a[e].y);return new Db("rect",new tb(b,d,c-b,f-d))}}
function Gb(a,b){var c;c=a.geometry.points;var d=0>rb(c)?-1:1;if(4>c.length)c=sb(c,d*b);else{for(var f=c.length-1,e=1,g=[],h=0;h<c.length;h++)f=sb([c[f],c[h],c[e]],d*b),g.push(f[1]),f=h,e++,e>c.length-1&&(e=0);c=g}return new Db("polygon",new qb(c))}
function Hb(a,b){if("rect"==a.type){var c=a.geometry,d=b({x:c.x,y:c.y}),c=b({x:c.x+c.width,y:c.y+c.height});return new Db("rect",new tb(d.x,d.y,c.x-d.x,c.y-d.y))}if("polygon"==a.type){var f=[];H(a.geometry.points,function(a){f.push(b(a))});return new Db("polygon",new qb(f))}}window.annotorious||(window.annotorious={});window.annotorious.geometry||(window.annotorious.geometry={},window.annotorious.geometry.expand=Gb);function Ib(a,b){var c=(ab||(ab=new I)).createElement("DIV");c.innerHTML=a(b||Jb,i,i);if(1==c.childNodes.length){var d=c.firstChild;if(1==d.nodeType)return d}return c}var Jb={};function Kb(){return l};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

 The "New" BSD License:

 Copyright (c) 2005-2009, The Dojo Foundation
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
 may be used to endorse or promote products derived from this software
 without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var Lb=function(){function a(a,c){if(!a)return[];if(a.constructor==Array)return a;if(!y(a))return[a];if(y(c)&&(c=y(c)?document.getElementById(c):c,!c))return[];var c=c||document,e=c.ownerDocument||c.documentElement;P=c.contentType&&"application/xml"==c.contentType||Da&&(c.doctype||"[object XMLDocument]"==e.toString())||!!e&&(B?e.xml:c.xmlVersion||e.xmlVersion);return(e=d(a)(c))&&e.H?e:b(e)}function b(a){if(a&&a.H)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;
G++;if(B&&P){var c=G+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(B&&a.xa)try{for(d=1;e=a[d];d++)wa(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0]._zipIdx=G);for(d=1;e=a[d];d++)a[d]._zipIdx!=G&&b.push(e),e._zipIdx=G}return b}function c(a,b){if(!b)return 1;var c=vc(a);return!b[c]?b[c]=1:0}function d(a,b){if(vb){var c=wb[a];if(c&&!b)return c}if(c=xb[a])return c;var c=a.charAt(0),e=-1==a.indexOf(" ");0<=a.indexOf("#")&&
e&&(b=l);if(vb&&!b&&-1==">~+".indexOf(c)&&(!B||-1==a.indexOf(":"))&&!(yb&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var g=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return wb[a]=function(b){try{if(!(9==b.nodeType||e))throw"";var c=b.querySelectorAll(g);B?c.xa=l:c.H=l;return c}catch(f){return d(a,l)(b)}}}var m=a.split(/\s*,\s*/);return xb[a]=2>m.length?f(a):function(a){for(var b=0,c=[],d;d=m[b++];)c=c.concat(f(d)(a));return c}}function f(a){var b=zb(ja(a));if(1==b.length){var c=
e(b[0]);return function(a){if(a=c(a,[]))a.H=l;return a}}return function(a){for(var a=da(a),c,d,f=b.length,ub,g,Ua=0;Ua<f;Ua++){g=[];c=b[Ua];d=a.length-1;0<d&&(ub={},g.H=l);d=e(c);for(var m=0;c=a[m];m++)d(c,g,ub);if(!g.length)break;a=g}return g}}function e(a){var b=Ab[a.r];if(b)return b;var c=a.ia,c=c?c.I:"",d=k(a,{q:1}),e="*"==a.d,f=document.getElementsByClassName;if(c)f={q:1},e&&(f.d=1),d=k(a,f),"+"==c?b=j(d):"~"==c?b=h(d):">"==c&&(b=g(d));else if(a.id)d=!a.ka&&e?Kb:k(a,{q:1,id:1}),b=function(b,
c){var e;e=b?new I(9==b.nodeType?b:b.ownerDocument||b.document):ab||(ab=new I);var f=a.id;if(f=(e=y(f)?e.R.getElementById(f):f)&&d(e))if(!(f=9==b.nodeType)){for(f=e.parentNode;f&&!(f==b);)f=f.parentNode;f=!!f}if(f)return da(e,c)};else if(f&&/\{\s*\[native code\]\s*\}/.test(""+f)&&a.j.length&&!yb)var d=k(a,{q:1,j:1,id:1}),m=a.j.join(" "),b=function(a,b){for(var c=da(0,b),e,f=0,g=a.getElementsByClassName(m);e=g[f++];)d(e,a)&&c.push(e);return c};else!e&&!a.ka?b=function(b,c){for(var d=da(0,c),e,f=0,
g=b.getElementsByTagName(a.S());e=g[f++];)d.push(e);return d}:(d=k(a,{q:1,d:1,id:1}),b=function(b,c){for(var e=da(0,c),f,g=0,uc=b.getElementsByTagName(a.S());f=uc[g++];)d(f,b)&&e.push(f);return e});return Ab[a.r]=b}function g(a){a=a||Kb;return function(b,d,e){for(var f=0,g=b[Bb];b=g[f++];)ea(b)&&(!e||c(b,e))&&a(b,f)&&d.push(b);return d}}function h(a){return function(b,d,e){for(b=b[fa];b;){if(ea(b)){if(e&&!c(b,e))break;a(b)&&d.push(b)}b=b[fa]}return d}}function j(a){return function(b,d,e){for(;b=b[fa];)if(!xa||
wa(b)){(!e||c(b,e))&&a(b)&&d.push(b);break}return d}}function k(a,b){if(!a)return Kb;var b=b||{},c=n;b.q||(c=Q(c,wa));b.d||"*"!=a.d&&(c=Q(c,function(b){return b&&b.tagName==a.S()}));b.j||H(a.j,function(a,b){var d=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=Q(c,function(a){return d.test(a.className)});c.count=b});b.l||H(a.l,function(a){var b=a.name;Va[b]&&(c=Q(c,Va[b](b,a.value)))});b.A||H(a.A,function(a){var b,d=a.Q;a.type&&Cb[a.type]?b=Cb[a.type](d,a.T):d.length&&(b=wc(d));b&&(c=Q(c,b))});b.id||a.id&&(c=
Q(c,function(b){return!!b&&b.id==a.id}));c||"default"in b||(c=Kb);return c}function r(a){return w(a)%2}function m(a){return!(w(a)%2)}function w(a){var b=a.parentNode,c=0,d=b[Bb],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&0<=e&&0<=f)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[fa])ea(b)&&(b._i=++c,a===b&&(e=c));return e}function q(a){for(;a=a[fa];)if(ea(a))return o;return l}function ya(a){for(;a=a[xc];)if(ea(a))return o;return l}function R(a,b){return!a?"":"class"==
b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(P?a.getAttribute(b):a.getAttribute(b,2))||""}function wa(a){return 1==a.nodeType}function Q(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function zb(a){function b(){0<=j&&(p.id=c(j,s).replace(/\\/g,""),j=-1);if(0<=k){var a=k==s?n:c(k,s);0>">~+".indexOf(a)?p.d=a:p.I=a;k=-1}0<=h&&(p.j.push(c(h+1,s).replace(/\\/g,"")),h=-1)}function c(b,d){return ja(a.slice(b,d))}for(var a=0<=">~+".indexOf(a.slice(-1))?
a+" * ":a+" ",d=[],e=-1,f=-1,g=-1,m=-1,h=-1,j=-1,k=-1,w="",q="",r,s=0,ya=a.length,p=n,x=n;w=q,q=a.charAt(s),s<ya;s++)if("\\"!=w)if(p||(r=s,p={r:n,l:[],A:[],j:[],d:n,I:n,id:n,S:function(){return P?this.Da:this.d}},k=s),0<=e)if("]"==q){x.Q?x.T=c(g||e+1,s):x.Q=c(e+1,s);if((e=x.T)&&('"'==e.charAt(0)||"'"==e.charAt(0)))x.T=e.slice(1,-1);p.A.push(x);x=n;e=g=-1}else"="==q&&(g=0<="|~^$*".indexOf(w)?w:"",x.type=g+q,x.Q=c(e+1,s-g.length),g=s+1);else 0<=f?")"==q&&(0<=m&&(x.value=c(f+1,s)),m=f=-1):"#"==q?(b(),
j=s+1):"."==q?(b(),h=s):":"==q?(b(),m=s):"["==q?(b(),e=s,x={}):"("==q?(0<=m&&(x={name:c(m+1,s),value:n},p.l.push(x)),f=s):" "==q&&w!=q&&(b(),0<=m&&p.l.push({name:c(m+1,s)}),p.ka=p.l.length||p.A.length||p.j.length,p.Ja=p.r=c(r,s),p.Da=p.d=p.I?n:p.d||"*",p.d&&(p.d=p.d.toUpperCase()),d.length&&d[d.length-1].I&&(p.ia=d.pop(),p.r=p.ia.r+" "+p.r),d.push(p),p=n);return d}function da(a,b){var c=b||[];a&&c.push(a);return c}var yb=D&&"BackCompat"==document.compatMode,Bb=document.firstChild.children?"children":
"childNodes",P=o,Cb={"*=":function(a,b){return function(c){return 0<=R(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==R(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+R(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+R(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+R(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return R(c,a)==b}}},xa=
"undefined"==typeof document.firstChild.nextElementSibling,fa=!xa?"nextElementSibling":"nextSibling",xc=!xa?"previousElementSibling":"previousSibling",ea=xa?wa:Kb,Va={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return ya},"last-child":function(){return q},"only-child":function(){return function(a){return!ya(a)||!q(a)?o:l}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===
c||3==c)return o}return l}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},not:function(a,b){var c=zb(b)[0],d={q:1};"*"!=c.d&&(d.d=1);c.j.length||(d.j=1);var e=k(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if("odd"==b)return r;if("even"==b)return m;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,g=-1;0<d?0>e?e=e%d&&d+e%d:0<e&&(e>=
d&&(f=e-e%d),e%=d):0>d&&(d*=-1,0<e&&(g=e,e%=d));if(0<d)return function(a){a=w(a);return a>=f&&(0>g||a<=g)&&a%d==e};b=e}var h=parseInt(b,10);return function(a){return w(a)==h}}},wc=B?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return P?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},Ab={},xb={},wb={},vb=!!document.querySelectorAll&&(!D||E("526")),G=0,vc=B?function(a){return P?a.getAttribute("_uid")||a.setAttribute("_uid",
++G)||G:a.uniqueID}:function(a){return a._uid||(a._uid=++G)};a.l=Va;return a}();aa("goog.dom.query",Lb);aa("goog.dom.query.pseudos",Lb.l);!B||Pa();var Mb=!B||Pa(),Nb=B&&!E("8");!D||E("528");C&&E("1.9b")||B&&E("8")||Da&&E("9.5")||D&&E("528");!C||E("8");function Ob(){}Ob.prototype.ga=o;Ob.prototype.B=function(){this.ga||(this.ga=l,this.C())};Ob.prototype.C=function(){this.za&&Pb.apply(n,this.za)};function Pb(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ba(d)?Pb.apply(n,d):d&&"function"==typeof d.B&&d.B()}};function L(a,b){this.type=a;this.currentTarget=this.target=b}ia(L,Ob);L.prototype.C=function(){delete this.type;delete this.target;delete this.currentTarget};L.prototype.U=o;L.prototype.na=l;L.prototype.preventDefault=function(){this.na=o};function Qb(a){Qb[" "](a);return a}Qb[" "]=function(){};function M(a,b){a&&this.init(a,b)}ia(M,L);t=M.prototype;t.target=n;t.relatedTarget=n;t.offsetX=0;t.offsetY=0;t.clientX=0;t.clientY=0;t.screenX=0;t.screenY=0;t.button=0;t.keyCode=0;t.charCode=0;t.ctrlKey=o;t.altKey=o;t.shiftKey=o;t.metaKey=o;t.h=n;
t.init=function(a,b){var c=this.type=a.type;L.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(C){var f;a:{try{Qb(d.nodeName);f=l;break a}catch(e){}f=o}f||(d=n)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=D||a.offsetX!==i?a.offsetX:a.layerX;this.offsetY=D||a.offsetY!==i?a.offsetY:a.layerY;this.clientX=a.clientX!==i?a.clientX:a.pageX;this.clientY=a.clientY!==i?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.h=a;delete this.na;delete this.U};t.preventDefault=function(){M.oa.preventDefault.call(this);var a=this.h;if(a.preventDefault)a.preventDefault();else if(a.returnValue=o,Nb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
t.C=function(){M.oa.C.call(this);this.relatedTarget=this.currentTarget=this.target=this.h=n};function Rb(){}var Sb=0;t=Rb.prototype;t.key=0;t.s=o;t.fa=o;t.init=function(a,b,c,d,f,e){if("function"==v(a))this.ja=l;else if(a&&a.handleEvent&&"function"==v(a.handleEvent))this.ja=o;else throw Error("Invalid listener argument");this.F=a;this.ma=b;this.src=c;this.type=d;this.capture=!!f;this.ha=e;this.fa=o;this.key=++Sb;this.s=o};t.handleEvent=function(a){return this.ja?this.F.call(this.ha||this.src,a):this.F.handleEvent.call(this.F,a)};var N={},O={},S={},T={};
function U(a,b,c,d,f){if(b){if("array"==v(b)){for(var e=0;e<b.length;e++)U(a,b[e],c,d,f);return n}var d=!!d,g=O;b in g||(g[b]={k:0,m:0});g=g[b];d in g||(g[d]={k:0,m:0},g.k++);var g=g[d],h=a[z]||(a[z]=++ga),j;g.m++;if(g[h]){j=g[h];for(e=0;e<j.length;e++)if(g=j[e],g.F==c&&g.ha==f){if(g.s)break;return j[e].key}}else j=g[h]=[],g.k++;e=Tb();e.src=a;g=new Rb;g.init(c,e,a,b,d,f);c=g.key;e.key=c;j.push(g);N[c]=g;S[h]||(S[h]=[]);S[h].push(g);a.addEventListener?(a==u||!a.ya)&&a.addEventListener(b,e,d):a.attachEvent(b in
T?T[b]:T[b]="on"+b,e);return c}throw Error("Invalid event type");}function Tb(){var a=Ub,b=Mb?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b}
function Vb(a){if(N[a]){var b=N[a];if(!b.s){var c=b.src,d=b.type,f=b.ma,e=b.capture;c.removeEventListener?(c==u||!c.ya)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in T?T[d]:T[d]="on"+d,f);c=c[z]||(c[z]=++ga);f=O[d][e][c];if(S[c]){var g=S[c];Sa(g,b);0==g.length&&delete S[c]}b.s=l;f.la=l;Wb(d,e,c,f);delete N[a]}}}
function Wb(a,b,c,d){if(!d.G&&d.la){for(var f=0,e=0;f<d.length;f++)d[f].s?d[f].ma.src=n:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.la=o;0==e&&(delete O[a][b][c],O[a][b].k--,0==O[a][b].k&&(delete O[a][b],O[a].k--),0==O[a].k&&delete O[a])}}function Xb(a,b,c,d,f){var e=1,b=b[z]||(b[z]=++ga);if(a[b]){a.m--;a=a[b];a.G?a.G++:a.G=1;try{for(var g=a.length,h=0;h<g;h++){var j=a[h];j&&!j.s&&(e&=Yb(j,f)!==o)}}finally{a.G--,Wb(c,d,b,a)}}return Boolean(e)}
function Yb(a,b){var c=a.handleEvent(b);a.fa&&Vb(a.key);return c}
function Ub(a,b){if(!N[a])return l;var c=N[a],d=c.type,f=O;if(!(d in f))return l;var f=f[d],e,g;if(!Mb){var h;if(!(h=b))a:{h=["window","event"];for(var j=u;e=h.shift();)if(j[e]!=n)j=j[e];else{h=n;break a}h=j}e=h;h=l in f;j=o in f;if(h){if(0>e.keyCode||e.returnValue!=i)return l;a:{var k=o;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(r){k=l}if(k||e.returnValue==i)e.returnValue=l}}k=new M;k.init(e,this);e=l;try{if(h){for(var m=[],w=k.currentTarget;w;w=w.parentNode)m.push(w);g=f[l];g.m=g.k;for(var q=
m.length-1;!k.U&&0<=q&&g.m;q--)k.currentTarget=m[q],e&=Xb(g,m[q],d,l,k);if(j){g=f[o];g.m=g.k;for(q=0;!k.U&&q<m.length&&g.m;q++)k.currentTarget=m[q],e&=Xb(g,m[q],d,o,k)}}else e=Yb(c,k)}finally{m&&(m.length=0),k.B()}return e}d=new M(b,this);try{e=Yb(c,d)}finally{d.B()}return e};function Zb(a,b,c){y(b)?$b(a,c,b):fb(b,ha($b,a))}function $b(a,b,c){a.style[ra(c)]=b}function ac(a,b,c){var d,f=C&&(va||Fa)&&E("1.9");o?(d=b.x,b=b.y):(d=b,b=c);a.style.left=bc(d,f);a.style.top=bc(b,f)}function cc(a,b,c){if(c==i)throw Error("missing height argument");a.style.width=bc(b,l);a.style.height=bc(c,l)}function bc(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a}
function dc(a,b){var c=a.style;"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*b+")")}function ec(a,b){a.style.display=b?"":"none"};function fc(a,b,c){this.i=a;this.u=b;this.b=c;this.z=[];this.p=[];this.e=this.i.getContext("2d");this.n=l;this.O=o;var d=this;U(this.i,"mousemove",function(a){if(d.n){var b=d.w(a.offsetX,a.offsetY);b?(d.O=o,d.c?d.c!=b&&(d.n=o,gc(d.u)):(d.c=b,V(d),d.b.fireEvent(hc,{annotation:d.c,mouseEvent:a}))):!d.O&&d.c&&(d.n=o,gc(d.u))}else d.t=a});W(c,X,function(){delete d.c;d.n=l});W(c,ic,function(){if(!d.n&&d.t){var a=d.c;d.c=d.w(d.t.offsetX,d.t.offsetY);d.n=l;a!=d.c?(V(d),d.b.fireEvent(jc,{annotation:a,mouseEvent:d.t}),
d.b.fireEvent(hc,{annotation:d.c,mouseEvent:d.t})):d.c&&kc(d.u)}else V(d)})}function lc(a,b){a.z.push(b);var c=b.shapes[0];"pixel"!=c.units&&(c=Hb(c,function(b){return a.b.Aa(b)}));a.p[JSON.stringify(b.shapes[0].geometry)]=c;V(a)}function mc(a,b){(a.c=b)?a.O=l:gc(a.u);V(a)}fc.prototype.w=function(a,b){var c=nc(this,a,b);if(0<c.length)return c[0]};
function nc(a,b,c){var d=[];H(a.z,function(f){var e;e=a.p[JSON.stringify(f.shapes[0].geometry)];if("rect"==e.type)e=b<e.geometry.x||c<e.geometry.y||b>e.geometry.x+e.geometry.width||c>e.geometry.y+e.geometry.height?o:l;else if("polygon"==e.type){e=e.geometry.points;for(var g=o,h=e.length-1,j=0;j<e.length;j++)e[j].y>c!=e[h].y>c&&b<(e[h].x-e[j].x)*(c-e[j].y)/(e[h].y-e[j].y)+e[j].x&&(g=!g),h=j;e=g}else e=o;e&&d.push(f)});Za(d,function(a,b){return Eb(a.shapes[0])>Eb(b.shapes[0])});return d}
function oc(a,b,c){var d=Ra(a.b.Ba(),function(a){return a.getSupportedShapeType()==b.type});d?d.drawShape(a.e,b,c):console.log("WARNING unsupported shape type: "+b.type)}function V(a){a.e.clearRect(0,0,a.i.width,a.i.height);H(a.z,function(b){oc(a,a.p[JSON.stringify(b.shapes[0].geometry)])});if(a.c){var b=a.p[JSON.stringify(a.c.shapes[0].geometry)];oc(a,b,l);b=Fb(b).geometry;a.u.show(a.c,{x:b.x,y:b.y+b.height+5})}};var Y=K;
function pc(a,b){function c(c){var d=o,f=c.relatedTarget||o;f||(d=l);ob(e,f)&&(d=l);var g;if(g=ob(b.editor.element[0],f))g=b.editor.annotation,g=!g?o:g.src==a.src;g&&(d=l);ob(b.viewer.element[0],f)&&qc(h)&&(d=l);c.h&&c.h.touches&&(d=o);return d}var d=Z(b.element[0].firstChild),f=new rc,e=kb("div","yuma-annotationlayer");Zb(e,"position","relative");cc(e,a.width,a.height);nb(e,a);e.appendChild(a);var g=Ib(sc,{width:a.width,height:a.height});e.appendChild(g);var h=new tc(a,b,f,d),j=Ib(sc,{width:a.width,height:a.height});
K.D||ec(j,o);e.appendChild(j);var k=new fc(g,h,f),r=new yc;r.init(j,f,k);new zc(f,e);f.pa=function(a){return a};f.Aa=function(a){return a};f.Ba=function(){return[r]};f.w=function(a,b){return k.w(a,b)};U(e,Y.W,function(a){c(a)||f.fireEvent(Ac)});U(e,Y.V,function(a){c(a)||f.fireEvent(X)});Bc(h,function(a){c(a)||f.fireEvent(Ac)});Cc(h,function(a){c(a)||f.fireEvent(X)});U(K.D?j:g,Y.qa,function(a){var b=Dc(a,g);a.preventDefault();ec(j,l);mc(k,i);r.startSelection(b.x,b.y)});W(f,Ac,function(){b.clearViewerHideTimer();
dc(g,1)});W(f,X,function(){dc(g,0.4)});W(f,Ec,function(c){var e={src:a.src,shapes:[c.shape]};b.publish("beforeAnnotationCreated",e);var f=Z(a),g=c.shape.geometry,c=g.x+f.left-d.left+16,f=g.y+g.height+f.top+window.pageYOffset-d.top+5;b.showEditor(e,{top:window.pageYOffset-d.top,left:0});ac(b.editor.element[0],c,f)});W(f,Fc,function(){K.D||ec(j,o);r.stopSelection()});b.viewer.on("edit",function(c){if(c.url==a.src){ec(j,l);mc(k,i);var e=Z(a),f=c.shapes[0].geometry,c=f.x+e.left-d.left+16,e=f.y+f.height+
e.top-d.top+window.pageYOffset+5;ac(b.editor.element[0],0,window.pageYOffset-d.top);b.editor.show();ac(b.editor.element[0],c,e)}});b.subscribe("annotationCreated",function(b){b.src==a.src&&(r.stopSelection(),b.src==a.src&&lc(k,new Gc(b.src,b.text,b.shapes[0])))});b.subscribe("annotationsLoaded",function(b){H(b,function(b){b.src==a.src&&lc(k,b)})});b.subscribe("annotationDeleted",function(b){b.src==a.src&&(b==k.c&&delete k.c,Sa(k.z,b),delete k.p[JSON.stringify(b.shapes[0].geometry)],V(k));f.fireEvent(ic)});
b.subscribe("annotationEditorHidden",function(){K.D||ec(j,o);r.stopSelection();f.fireEvent(ic)})}window.Annotator.Plugin.AnnotoriousImagePlugin=function(){function a(a){this.ta=a}a.prototype.pluginInit=function(){var a=this;H(this.ta.getElementsByTagName("img"),function(c){new pc(c,a.annotator)})};return a}();Y=K;function tc(a,b,c,d){this.Z=a;this.g=b;this.ua=c;this.K=d;this.L=o;this.ca=[];this.ba=[];var f=this;U(this.g.viewer.element[0],Y.W,function(a){qc(f)&&(kc(f),H(f.ca,function(b){b(a)}))});U(this.g.viewer.element[0],Y.V,function(a){qc(f)&&(b.clearViewerHideTimer(),gc(f),H(f.ba,function(b){b(a)}))})}function qc(a){var b=a.g.viewer.annotations;return!b||1>b.length?o:b[0].src==a.Z.src}function Bc(a,b){a.ca.push(b)}function Cc(a,b){a.ba.push(b)}
function gc(a){0<=Qa(cb(a.g.viewer.element[0]),"annotator-hide")||(a.L=o,a.v||(a.v=window.setTimeout(function(){a.ua.fireEvent(ic);!a.L&&qc(a)&&(db(a.g.viewer.element[0],"annotator-hide"),a.g.viewer.annotations=[],delete a.v)},300)))}function kc(a){a.L=l;a.v&&(window.clearTimeout(a.v),delete a.v)}
tc.prototype.show=function(a,b){eb(this.g.viewer.element[0],"annotator-hide");var c=Z(this.Z);ac(this.g.viewer.element[0],0,window.pageYOffset-this.K.top);this.g.viewer.load([a]);ac(this.g.viewer.element[0],c.left-this.K.left+b.x+16,c.top+window.pageYOffset-this.K.top+b.y);kc(this)};function yc(){}t=yc.prototype;t.init=function(a,b,c){this.i=a;this.viewer=c;this.b=b;this.e=a.getContext("2d");this.e.lineWidth=1;this.M=o};
t.J=function(){var a=this,b=this.i;this.P=U(this.i,K.ra,function(c){c=Dc(c,b);if(a.M){a.f={x:c.x,y:c.y};a.e.clearRect(0,0,b.width,b.height);var c=a.f.x-a.a.x,d=a.f.y-a.a.y;a.e.strokeStyle="#000000";a.e.strokeRect(a.a.x+0.5,a.a.y+0.5,c,d);a.e.strokeStyle="#ffffff";0<c&&0<d?a.e.strokeRect(a.a.x+1.5,a.a.y+1.5,c-2,d-2):0<c&&0>d?a.e.strokeRect(a.a.x+1.5,a.a.y-0.5,c-2,d+2):0>c&&0>d?a.e.strokeRect(a.a.x-0.5,a.a.y-0.5,c+2,d+2):a.e.strokeRect(a.a.x-0.5,a.a.y+1.5,c+2,d-2)}});this.aa=U(b,K.sa,function(c){var d=
Dc(c,b),f;a.getShape();c=c.h?c.h:c;a.M=o;if(f=a.getShape())a.b.fireEvent(Ec,{mouseEvent:c,shape:f,viewportBounds:a.getViewportBounds()});else if(a.b.fireEvent(Fc),c=a.b.w(d.x,d.y))d=document,type="HTMLEvents",f=document.createEvent("HTMLEvents"),f.initEvent("annotoriousSelectsAnnotation"),f.data=c||{},d.dispatchEvent(f),mc(a.viewer,c)})};t.X=function(){this.P&&(Vb(this.P),delete this.P);this.aa&&(Vb(this.aa),delete this.Fa)};t.getSupportedShapeType=function(){return"rect"};
t.startSelection=function(a,b){var c={x:a,y:b};this.M=l;this.J(c);this.a=new pb(a,b);this.b.fireEvent(Hc,{offsetX:a,offsetY:b});Zb(document.body,"-webkit-user-select","none")};t.stopSelection=function(){this.X();this.e.clearRect(0,0,this.i.width,this.i.height);Zb(document.body,"-webkit-user-select","auto");delete this.f};
t.getShape=function(){if(this.f&&3<Math.abs(this.f.x-this.a.x)&&3<Math.abs(this.f.y-this.a.y)){var a=this.getViewportBounds(),b=this.b.pa({x:a.left,y:a.top}),a=this.b.pa({x:a.right-1,y:a.bottom-1});return new Db("rect",new tb(b.x,b.y,a.x-b.x,a.y-b.y))}};t.getViewportBounds=function(){var a,b;this.f.x>this.a.x?(a=this.f.x,b=this.a.x):(a=this.a.x,b=this.f.x);var c,d;this.f.y>this.a.y?(c=this.a.y,d=this.f.y):(c=this.f.y,d=this.a.y);return{top:c,right:a,bottom:d,left:b}};
t.drawShape=function(a,b,c){if("rect"==b.type){var d;c?(c="#fff000",d=1.2):(c="#ffffff",d=1);b=b.geometry;a.strokeStyle="#000000";a.lineWidth=d;a.strokeRect(b.x+0.5,b.y+0.5,b.width+1,b.height+1);a.strokeStyle=c;a.strokeRect(b.x+1.5,b.y+1.5,b.width-1,b.height-1)}};function Gc(a,b,c){this.src=a;this.text=b;this.shapes=[c];this.context=document.URL};function Z(a){for(var b=0,c=0;a&&!isNaN(a.offsetLeft)&&!isNaN(a.offsetTop);)b+=a.offsetLeft-a.scrollLeft,c+=a.offsetTop-a.scrollTop,a=a.offsetParent;return{top:c,left:b}};function rc(){this.o=[]}function Dc(a,b){var c=o;return c=!a.offsetX||!a.offsetY&&a.h.changedTouches?{x:a.h.changedTouches[0].pageX-Z(b).left,y:a.h.changedTouches[0].pageY-Z(b).top}:{x:a.offsetX,y:a.offsetY}}function W(a,b,c){a.o[b]||(a.o[b]=[]);a.o[b].push(c)}rc.prototype.fireEvent=function(a,b){var c=o,d=this.o[a];d&&H(d,function(a){a=a(b);a!==i&&!a&&(c=l)});return c};
var Ac="onMouseOverItem",X="onMouseOutOfItem",hc="onMouseOverAnnotation",jc="onMouseOutOfAnnotation",Hc="onSelectionStarted",Fc="onSelectionCanceled",Ec="onSelectionCompleted",ic="beforePopupHide";function zc(a,b,c){var d=this;c||(c="Click and Drag to Annotate");this.element=Ib(Ic,{Ca:c});this.b=a;this.$=Lb(".annotorious-hint-msg",this.element)[0];this.Y=Lb(".annotorious-hint-icon",this.element)[0];this.ea=function(){d.show()};this.da=function(){Jc(d)};this.J();Jc(this);b.appendChild(this.element)}zc.prototype.J=function(){var a=this;this.wa=U(this.Y,"mouseover",function(){a.show();window.clearTimeout(a.N)});this.va=U(this.Y,"mouseout",function(){Jc(a)});W(this.b,Ac,this.ea);W(this.b,X,this.da)};
zc.prototype.X=function(){Vb(this.wa);Vb(this.va);var a=this.b.o[Ac];a&&Sa(a,this.ea);(a=this.b.o[X])&&Sa(a,this.da)};zc.prototype.show=function(){window.clearTimeout(this.N);dc(this.$,0.8);var a=this;this.N=window.setTimeout(function(){Jc(a)},3E3)};function Jc(a){window.clearTimeout(a.N);dc(a.$,0)};B&&E(8);"ScriptEngine"in u&&"JScript"==u.ScriptEngine()&&(u.ScriptEngineMajorVersion(),u.ScriptEngineMinorVersion(),u.ScriptEngineBuildVersion());function Kc(a){return"object"===typeof a&&a&&0===a.Ga?a.content:(""+a).replace(Lc,Mc)}var Nc={"\x00":"&#0;",'"':"&quot;","&":"&amp;","'":"&#39;","<":"&lt;",">":"&gt;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\u000c":"&#12;","\r":"&#13;"," ":"&#32;","-":"&#45;","/":"&#47;","=":"&#61;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function Mc(a){return Nc[a]}var Lc=/[\x00\x22\x26\x27\x3c\x3e]/g;function sc(a){return'<canvas class="annotorious-item annotorious-opacity-fade" style="position:absolute; top:0px; left:0px; width:'+Kc(a.width)+"px; height:"+Kc(a.height)+'px; z-index:0" width="'+Kc(a.width)+'" height="'+Kc(a.height)+'"></canvas>'}
function Ic(a){return'<div class="annotorious-hint" style="white-space:nowrap; position:absolute; top:0px; left:0px; pointer-events:none;"><div class="annotorious-hint-msg annotorious-opacity-fade">'+Kc(a.Ca)+'</div><div class="annotorious-hint-icon" style="pointer-events:auto"></div></div>'};
